### ISSUE TITLE
Paragrafer i databasen

### ISSUE THREAD

**Issue by einarlove** [einarlove/einarlove.com#2]
All tekst som jeg bruker har jeg delt opp i paragrafer `<p>` , og for midlertidig skyld har jeg bare lagret teksten sammen med paragraf og link tagene i databasen. Det er lite elegant å be brukeren forholde seg til `<p>` og `<a>` når man redigere det etterpå i CMS løsningen, så hvordan ville du løst dette?
Hadde det vært lurest å legge det inn med en type formatering, som så legger på paragrafer når ruby rendrer det, eller gjøre det motsatt og gjøre html tags om til markdown når man skal redigere i CMS ?

**Comment by ovelar** [comment]
Det er to forskjellige måter å gjøre dette på, enten client side med en editor som Aloha eller en annen wysiwyg greie, eller server side med en gem som f.eks. redcloth.
