### ISSUE TITLE
Flere tips og triks

### ISSUE THREAD

**Issue by einarlove** [einarlove/einarlove.com#3]
Hvis du ser noe annet som jeg har gjort vanskeligere en normalt eller slikt, så er det bare å rette på meg eller gi tips.
Har innlevering tirsdag og mye igjen å gjøre, så får ikke tid til å søke opp best practices på alt, og vet ikke så mye siden jeg er ny.
Som mitt nye table `portfolio`. Hvis jeg skal lage ny row in det table, så skriver jeg `new_portfolio`. Hvordan rename jeg plural form av portfolio til `new_portfolio_item`? 
Leste at man kunne skrive i modellen `has_many`, men fikk bare mange feilmeldinger.

**Comment by einarlove** [comment]
Såg for meg noe lignende:

``` Ruby
class Portfolio < ActiveRecord::Base
  belongs_to :pages
  has_many :portfolio_items
end
```

Men har ingen anelse hvordan jeg skulle ta i bruk av dette. Har en følelse på at jeg trenger flere tables til det, og det er uaktuelt.

**Comment by ovelar** [comment]
Skavvise, jeg ville egentlig droppa hele portfoliotabellen, og heller kun hatt portfolio_items. Sånn at du da kan liste ut disse portfolio_items, som jeg regner med er jobber du har gjort under en side du kaller portfolio. Denne siden kan godt være en named route under PagesController f.eks., eller en egen controller som heter PortfolioItemsController. Skal ta en titt rundt i koden og se om jeg snapper opp noe annet kjapt.

**Comment by ovelar** [comment]
Et par kjappe:
- Modeller bør ha entallsnavn, ie: page.rb
- Tabeller bør ha flertallsnavn, ie: pages

Dette for å bruke magien som ligger i Rails med collections av ting.

Et par ting som går på coding convention også, ser det er litt ujevn indentation et par steder som kan være greit å fikse opp for lesbarhet. Selv liker jeg å følge https://github.com/styleguide/ruby relativt slavisk.

**Comment by einarlove** [comment]
I den nyeste pullen gjorde jeg det første.
Angående coding convetion så vet jeg ærlig talt ikke hva jeg har gjort galt. Kan være at scaffold genererte spaces mens jeg lager indents og det er det som ser ujevnt hos deg i textmate osv.

**Comment by ovelar** [comment]
Ja, ser ut som det er tabs istedet for spaces. Vanligvis bruker man to space, istedet for tab som indentation, men det er flisespikkeri :) Si ifra om det er noe mer du vil ha svar på før innlevering.

**Comment by einarlove** [comment]
Holder på å klikke banalt av denne convenient asset pipeline. 
Har prøvd å la rails trolldommen ta sin afære, men nå som jeg skal legge til fonts med `@font-face`, så vil det ikke fungere.
Har prøvd ut embeded ruby i css filen som `font_path`, `asset_path`osv. La også inn `config.assets.paths << Rails.root.join("app", "assets", "fonts")`, men får fordsatt `GET http://einarlove.dev/assets/pillgothic300mg-regular.ttf 404 (Not Found)`. skal pushe opp nyeste commiten.
Er litt furten siden kort tidsfrist, mye å gjøre og heruko var ikke vennlig når det kom til databasen.

**Comment by ovelar** [comment]
Ser ut som du fikk orden på det? Jeg får ihvertfall ikke 404 på fontene nå. Jeg har ikke brukt vanilla CSS på flere år, men i SASS/SCSS har du en helper som heter font-url() som du kan bruke for å linke til fonter i app/assets/fonts eller vendor/assets/fonts - gjør vel basically det samme som du har gjort her.

**Comment by einarlove** [comment]
Hvilken gem ville du anbeflalt for en kontaktskjema?

**Comment by ovelar** [comment]
Jeg ville skrevet kontaktskjema for hånd tror jeg. Såvidt jeg vet finnes det ingen gems som gir deg den funksjonaliteten du har lyst på. Sjekk ut f.eks. denne guiden: http://matharvard.ca/posts/2011/aug/22/contact-form-in-rails-3/
